### PR TITLE
Update to 21.12.3

### PR DESCRIPTION
**Pull request by flyingcakes85**

### CODE REVIEW

**Comment by flyingcakes85** [comment]
`Error in the HTTP2 framing layer`

**Comment by tsdgeos** [comment]
bot, build

**Comment by tsdgeos** [comment]
bot, build

**Comment by flyingcakes85** [comment]
`Failed to download sources: module libkdepim: Error in the HTTP2 framing layer`

Surprisingly, I got similar errors multiple times yesterday :thinking:

**Comment by tsdgeos** [comment]
there's somethign always wrong with kontact in flathub, noone understands why

**Comment by tsdgeos** [comment]
bot, build

**Pull request merged**
