### PR TITLE
Update KDE Runtime to 5.15-21.08

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by travier** [comment]
OK, now we can try to figure out what's missing for this one! 🙂

**Comment by travier** [comment]
bot, build

**Comment by tsdgeos** [comment]
We can remove a few things that are now in the sdk i think:

Maybe? options are sufficiently different that maybe this is not good enough?
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/21.08/elements/components/cyrus-sasl.bst

This seems fine
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/21.08/elements/components/gpgme.bst

This seems fine
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/21.08/elements/components/libgpg-error.bst

This seems fine
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/21.08/elements/components/libassuan.bst

**Comment by tsdgeos** [comment]
Are you sure about the cyrus removal? Personally unless you're 100% sure i'd leave it.

About the xapian build error, maybe update the tarball to 1.14.18? With a bit of luck they added the missing include in that version, otherwise we'll have to locally patch it

**Comment by travier** [comment]
> Are you sure about the cyrus removal? Personally unless you're 100% sure i'd leave it.

Indeed, I misread your first message. Let's keep it for now.

**Comment by travier** [comment]
bot, build

**Comment by tsdgeos** [comment]
Have you tried without gpgme? it'd seem that there's one in the runtime that may be enough?

**Comment by travier** [comment]
From memory it failed on missing the Qt support with the runtime provided gpgme.

**Comment by tsdgeos** [comment]
ok, i guess you can merge, but we should investigate why that buidl failure is happening because it doesn't feel like a good idea to have two copies of the same library around

**Comment by travier** [comment]
Pushed a commit to verify what I've mentioned above.

**Comment by travier** [comment]
bot, build

**Comment by travier** [comment]
```
========================================================================
Building module libkleo in /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/build/libkleo-1
========================================================================
]2;flatpak-builder: Building libkleoFB: Running: tar xf /srv/buildbot/worker/downloads/downloads/572de9a37b6c56a1aaa23f5cb5e9d7ae1250a24ed2a0746574872081edf5a5d6/libkleo-21.12.0.tar.xz --no-same-owner --strip-components=1 -J
FB: Running 'flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/libkleo --nofilesystem=host --filesystem=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/build/libkleo-1 --bind-mount=/run/build/libkleo=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/build/libkleo-1 --build-dir=/run/build/libkleo --bind-mount=/run/ccache=/srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/ccache --unshare=network --env=SOURCE_DATE_EPOCH=1641811325 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=48 /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-0BEle3 cmake '-DCMAKE_INSTALL_PREFIX:PATH='\''/app'\''' -G Ninja . -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo' on host
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Installing in /app. Run /run/build/libkleo/prefix.sh to set the environment for libkleo.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
-- Could NOT find KF5PimTextEdit (missing: KF5PimTextEdit_DIR)
-- Could NOT find QGpgme (missing: QGpgme_DIR)
CMake Error at CMakeLists.txt:49 (find_package):
  Could not find a package configuration file provided by "QGpgme" (requested
  version 1.13.1) with any of the following names:
    QGpgmeConfig.cmake
    qgpgme-config.cmake
  Add the installation prefix of "QGpgme" to CMAKE_PREFIX_PATH or set
  "QGpgme_DIR" to a directory containing one of the above files.  If "QGpgme"
  provides a separate development package or SDK, be sure it has been
  installed.
-- Configuring incomplete, errors occurred!
See also "/run/build/libkleo/CMakeFiles/CMakeOutput.log".
FB: host_command_exited_cb 2551460 256
]2;flatpak-builder: Cleanup libkleoError: module libkleo: Child process exited with code 1
```

**Comment by travier** [comment]
bot, build

**Pull request merged**
