### PR TITLE
Version update

### PR DESCRIPTION
**Pull request by tsdgeos**

### CODE REVIEW

**Comment by Justinzobel** [comment]
libetebase upgrade caused a failure. I believe it's to do with rust dependency building?

**Comment by Justinzobel** [comment]
Patch fb0d78fb3bcfce5bd4ff7f51e4cd1405693e0275 failing to apply in kdepim-runtime, 

https://invent.kde.org/pim/kdepim-runtime/-/commit/fb0d78fb3bcfce5bd4ff7f51e4cd1405693e0275 says it's in the 23.08 branch so should not be needed any more.

**Comment by Justinzobel** [comment]
Just need "-DENABLE_QT6=OFF" in poppler's build now hopefully :crossed_fingers:

**Comment by tsdgeos** [comment]
bot, build

**Pull request merged**
