### PR TITLE
Update QCA to 2.3.4

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by travier** [comment]
bot, build

**Comment by travier** [comment]
Failed on something unrelated:
```
• attribute-invalid     : <screenshot> width (1280) did not match specified (1607) [https://kontact.kde.org/assets/img/appstream/kontact-korganizer.png]
• attribute-invalid     : <screenshot> height (720) did not match specified (1039) [https://kontact.kde.org/assets/img/appstream/kontact-korganizer.png]
```

**Comment by travier** [comment]
@tsdgeos Do you know who updates those images?

**Comment by tsdgeos** [comment]
https://invent.kde.org/websites/kontact-kde-org/-/tree/master/assets/img/appstream

In this case it seems seem Glen did it https://invent.kde.org/websites/kontact-kde-org/-/merge_requests/5

**Comment by travier** [comment]
Closing in favor of https://github.com/flathub/org.kde.kontact/pull/54

**Pull request closed without merging**
