### PR TITLE
Version update

### PR DESCRIPTION
**Pull request by tsdgeos**

### CODE REVIEW

**Comment by tsdgeos** [comment]
bot, build

**Comment by tsdgeos** [comment]
@barthalion Any idea why we get all those "Error in the HTTP2 framing layer" when downloading?

**Comment by barthalion** [comment]
`downloaded-sources` allows download failures now, the actual build failure is this:

```
========================================================================
Building module akregator in /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/build/akregator-1
========================================================================
]2;flatpak-builder: Building akregatorFB: Running: tar xf /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/downloads/b5c6bbeb9c5ad0ae3d0b55391fa940da084175ffcbd6e6244036efe3464d3b0f/akregator-21.08.1.tar.xz --no-same-owner --strip-components=1 -J
Applying patch akregator-arm32-fix-namelookup.patch
FB: Running: patch -p1 -i /srv/buildbot/worker/build-x86_64-7/build/akregator-arm32-fix-namelookup.patch
patching file configuration/akregator_config_plugins.cpp
Hunk #1 FAILED at 13.
1 out of 1 hunk FAILED -- saving rejects to file configuration/akregator_config_plugins.cpp.rej
]2;flatpak-builder: Cleanup akregatorError: module akregator: Child process exited with code 1
FB: Unmounting read-only fs: fusermount -uz /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/rofiles/rofiles-jPjt8Y
```

**Comment by tsdgeos** [comment]
> `downloaded-sources` allows download failures now, the actual build failure is this:

Sure i do know there's an issue somewhere, it just looks super weird that downloads fail all the time :/

**Comment by barthalion** [comment]
> > `downloaded-sources` allows download failures now, the actual build failure is this:
> 
> Sure i do know there's an issue somewhere, it just looks super weird that downloads fail all the time :/

Seems it works now. Maybe we were being redirected to some semi-broken mirror?

**Comment by tsdgeos** [comment]
> > > `downloaded-sources` allows download failures now, the actual build failure is this:
> > 
> > 
> > Sure i do know there's an issue somewhere, it just looks super weird that downloads fail all the time :/
> 
> Seems it works now. Maybe we were being redirected to some semi-broken mirror?

Maybe

**Comment by travier** [comment]
Closing in favor of https://github.com/flathub/org.kde.kontact/pull/54 where I picked those commits.

**Pull request closed without merging**
