### PR TITLE
Drop bundled sqlite

### PR DESCRIPTION
**Pull request by Erick555**
Try using the sqlite from runtime for better compatibility

Fixes https://github.com/flathub/org.kde.kontact/issues/208

### CODE REVIEW

**Comment by travier** [comment]
@andrevmatos Can you test this one?

**Comment by travier** [comment]
According to @tsdgeos we can not do that as we need the additional options used to compile sqlite for the application compared to the one in the Runtime.

**Comment by travier** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/freedesktop-sdk-22.08.14/elements/components/sqlite.bst

**Comment by Erick555** [comment]
Do you mean `--enable-threadsafe` and `--enable-threads-override-locks`? What happens if they're missing?

At least someone could try it this fixes the symbol errors.

**Comment by Erick555** [comment]
Actually the [logs](https://buildbot.flathub.org/api/v2/logs/2445241/raw) from other PR show:
`configure: WARNING: unrecognized options: --enable-threads-override-locks`

Also` --enable-threadsafe` is the [default](https://github.com/sqlite/sqlite/blob/a7ec1f9a1b0415336079baa9a6073d37350c8331/autoconf/configure.ac#L88)
`[--enable-threadsafe], [build a thread-safe library [default=yes]])],`

So above are just some form of cargo cult. There are no other differences from https://github.com/flathub/org.kde.kontact/pull/207

**Comment by danvratil** [comment]
I think back in the day there either was not solitér in the runtime, or it did not have the right compile options enabled.

Nowadays Akonadi will work just fine with default sqlite configuration, so if a reasonably modern sqlite is available in the runtime, I'm pretty sure the custom build of sqlite can be dropped from the Akonadi flatpak.

**Comment by travier** [comment]
OK, I've got a confirmation from someone that this works + 2 other folks confirming the change so I'll merge this.

**Review by travier — APPROVED** [review]

**Pull request merged**
