### PR TITLE
Version update

### PR DESCRIPTION
**Pull request by tsdgeos**

### CODE REVIEW

**Comment by CarlSchwan** [comment]
It seems the build timed out :/

**Comment by tsdgeos** [comment]
bot, build

**Comment by tsdgeos** [comment]
bot, build

**Comment by tsdgeos** [comment]
man such broken builders

**Comment by tsdgeos** [comment]
bot, build

**Comment by travier** [comment]
ot, build

**Comment by travier** [comment]
(This needs https://github.com/flathub/org.kde.kontact/pull/55)

**Comment by travier** [comment]
This might be fixed with https://github.com/flathub/org.kde.kontact/pull/55

**Comment by tsdgeos** [comment]
bot, build

**Comment by travier** [comment]
bot, build

**Comment by travier** [comment]
bot, build

**Comment by travier** [comment]
x86_64 successful, aarch64 failed due to timeouts.
bot, build

**Pull request merged**
